version: '3'

services:
  web_api:
    container_name: travel-map_web_api
    image: asudre/travel-map:api_latest
    depends_on: ['database']
    ports:
      - '8080:8080'
    env_file:
      - ./api/docker/env.conf

  web_public:
    container_name: travel-map_web_public
    image: asudre/travel-map:public_latest
    depends_on: ['web_api']
    ports:
      - '8081:8081'

  database:
    container_name: travel-map_database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo:
